version: '3.8'
services:
  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:optimism
    restart: unless-stopped
    ports:
      - "127.0.0.1:9546:8545"
      - "127.0.0.1:8552:8551"
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    environment:
      L2_CHAIN_ID: ${L2_CHAIN_ID}
    volumes:
      - geth_sepolia_data:/root/.ethereum
      - ./entrypoint.sh:/entrypoint.sh
      - ./jwt.txt:/config/jwt.txt
      - ../configs/genesis.sepolia.json:/config/genesis.json

  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:latest
    restart: unless-stopped
    depends_on:
      - op-geth
    ports:
      - "127.0.0.1:7546:9545"
    volumes:
      - ./jwt.txt:/config/jwt.txt
      - ../configs/rollup.sepolia.json:/config/rollup.sepolia.json
    command: >
      op-node
      --rollup.config=/config/rollup.sepolia.json
      --l1=${L1_RUNTIME_RPC_URL}
      --l1.beacon=${L1_BEACON_URL}
      --l1.epoch-poll-interval=12s
      --l1.http-poll-interval=12s
      --l2=http://op-geth:8551
      --l2.jwt-secret=/config/jwt.txt
      --rollup.load-protocol-versions=false
      --sequencer.enabled
      --sequencer.l1-confs=4
      --verifier.l1-confs=4
      --rpc.addr=0.0.0.0
      --rpc.port=9545
      --metrics.enabled
      --metrics.addr=0.0.0.0
      --metrics.port=7300
      --p2p.disable

  op-batcher:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-batcher:latest
    restart: unless-stopped
    depends_on:
      - op-geth
      - op-node
    command: >
      op-batcher
      --l1-eth-rpc=${L1_RUNTIME_RPC_URL}
      --l2-eth-rpc=http://op-geth:8545
      --rollup-rpc=http://op-node:9545
      --private-key=${BATCHER_PRIVATE_KEY}
      --data-availability-type=calldata
      --poll-interval=6s
      --max-channel-duration=20
      --max-l1-tx-size-bytes=120000
      --sub-safety-margin=8
      --num-confirmations=4
      --resubmission-timeout=30s
      --safe-abort-nonce-too-low-count=3
      --throttle.unsafe-da-bytes-lower-threshold=0
      --metrics.enabled
      --metrics.addr=0.0.0.0
      --metrics.port=7300
      --log.level=info

  op-proposer:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-proposer:latest
    restart: unless-stopped
    depends_on:
      - op-node
    command: >
      op-proposer
      --l1-eth-rpc=${L1_RUNTIME_RPC_URL}
      --rollup-rpc=http://op-node:9545
      --game-factory-address=${DGF_ADDRESS}
      --game-type=${GAME_TYPE}
      --private-key=${PROPOSER_PRIVATE_KEY}
      --allow-non-finalized
      --wait-node-sync
      --poll-interval=12s
      --proposal-interval=120s
      --num-confirmations=4
      --resubmission-timeout=30s
      --metrics.enabled
      --metrics.addr=0.0.0.0
      --metrics.port=7300
      --log.level=info

volumes:
  geth_sepolia_data:
