version: '3.8'
services:
  l1:
    image: ghcr.io/foundry-rs/foundry:latest
    ports:
      - "8545:8545"
    entrypoint: anvil
    command: --host 0.0.0.0 --block-time 12 --chain-id 31337 --timestamp ${L1_GENESIS_TIMESTAMP:-1777670160}

  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:optimism
    depends_on:
      - l1
    ports:
      - "9545:8545"
      - "8551:8551"
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    volumes:
      - geth_data:/root/.ethereum
      - ./entrypoint.sh:/entrypoint.sh
      - ./jwt.txt:/config/jwt.txt
      - /Users/piyushutkar/Desktop/Veltrix/configs/genesis.json:/config/genesis.json

  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:latest
    depends_on:
      - l1
      - op-geth
    ports:
      - "7545:9545"
    volumes:
      - ./jwt.txt:/config/jwt.txt
      - /Users/piyushutkar/Desktop/Veltrix/configs:/config
    command: >
      op-node --rollup.config=/config/rollup.json
      --rollup.l1-chain-config=/config/l1-chain-config.json
      --l1=http://l1:8545
      --l1.beacon.ignore
      --l2=http://op-geth:8551
      --l2.jwt-secret=/config/jwt.txt
      --rollup.load-protocol-versions=false
      --l1.trustrpc
      --sequencer.enabled
      --sequencer.l1-confs=0
      --verifier.l1-confs=0
      --rpc.addr=0.0.0.0
      --rpc.port=9545
      --metrics.enabled
      --metrics.addr=0.0.0.0
      --metrics.port=7300
      --p2p.disable

  op-batcher:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-batcher:latest
    depends_on:
      - l1
      - op-geth
      - op-node
    command: >
      op-batcher
      --l1-eth-rpc=http://l1:8545
      --l2-eth-rpc=http://op-geth:8545
      --rollup-rpc=http://op-node:9545
      --private-key=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      --data-availability-type=calldata
      --poll-interval=1s
      --max-channel-duration=1
      --max-l1-tx-size-bytes=60000
      --sub-safety-margin=4
      --num-confirmations=1
      --resubmission-timeout=10s
      --safe-abort-nonce-too-low-count=3
      --throttle.unsafe-da-bytes-lower-threshold=0
      --metrics.enabled
      --metrics.addr=0.0.0.0
      --metrics.port=7300
      --log.level=info

  op-proposer:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-proposer:latest
    profiles:
      - proposer
    depends_on:
      - l1
      - op-node
    command: >
      op-proposer
      --l1-eth-rpc=http://l1:8545
      --rollup-rpc=http://op-node:9545
      --game-factory-address=0xda5724A71FCbd2813776d13A0b7b4641EB7D678E
      --game-type=254
      --private-key=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
      --allow-non-finalized
      --poll-interval=6s
      --proposal-interval=12s
      --num-confirmations=1
      --resubmission-timeout=10s
      --metrics.enabled
      --metrics.addr=0.0.0.0
      --metrics.port=7300
      --log.level=info

volumes:
  geth_data:
